---
default_config:
logger:
  default: info
  logs:
    racelandshop: debug
    custom_components.racelandshop: debug
frontend:
  themes: !include_dir_merge_named themes
#racelandshop:
#  token: CHANGE_ME
#  sidepanel_title: RACELANDSHOP
#  sidepanel_icon: racelandshop:racelandshop
#  frontend_repo: "/workspaces/development/repositories/frontend"
#  appdaemon: true
#  experimental: true
#  country: "ALL"
#  release_limit: 5
